# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('aname', models.CharField(max_length=100)),
                ('asalary', models.IntegerField()),
                ('tcity', models.CharField(max_length=20)),
                ('saddress', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('srolno', models.IntegerField()),
                ('smarks', models.IntegerField()),
                ('saddress', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
                ('tsalary', models.IntegerField()),
                ('tcity', models.CharField(max_length=20)),
                ('saddress', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
